### ISSUE TITLE
Feature request: used/unused cuts

### ISSUE THREAD

**Issue by dranorter** [grigorusha/GeraniumsPot#4]
Geraniums Pot is a great prototyping tool for puzzles. Back when I designed my puzzles I did something much more time-consuming in Inkscape to test the rotation. The one feature I'm missing, that I had in Inkscape, is testing which edges of the puzzle actually can be scrambled.

The feature would be a bit like this. With a physical puzzle, starting from the solved state, put a little sticker on each place where two pieces meet. Then, scramble the puzzle, letting the stickers tear when the puzzle moves. The point is to check that each sticker can be torn in the course of a full scramble.

Geraniums Pot doesn't present itself as a prototyping tool, so really this is out of scope. But from a prototyping point of view, it would be really useful to be able to check that a puzzle does fully scramble.

**Comment by grigorusha** [comment]
Unfortunately I don't know how to do this. you can run a very long scramble procedure (F8 button) or even repeat it several times. but this does not guarantee that all the parts will separate correctly

**Comment by dranorter** [comment]
Yeah, my puzzles are very resistant to auto-scrambling and I often need to make moves myself to get certain pieces separated. And getting everything separated simultaneously is an extra challenge.

The feature request was a long shot, thanks for giving it a little thought!

**Comment by grigorusha** [comment]
A simple Random function will not cope with this. To do this correctly maybe me need to study group theory.
I encountered this problem when I made bandaged cubes in pcubes. These puzzles are also very difficult to confuse automatically.
